#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  require "dotenv/load"
rescue LoadError
  # dotenv is optional for CLI usage
end

require "broadlistening"

Broadlistening::CLI.new(ARGV).run
